flask_user/user/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class UserForm(FlaskForm):

    url = StringField('Website URL', validators = [DataRequired()])
    submit = SubmitField('Start')

flask_user/user/routes.py
from flask import render_template, Blueprint, Response, redirect, url_for
from user.forms import UserForm
from camera import VideoCamera
import time
import matplotlib
import matplotlib.pyplot as mpl
import numpy as np

users = Blueprint('users', __name__)
emotionDict = {"joy": 0, "surprise": 0, "sorrow": 0, "anger": 0}
allEmotionDicts = {}

@users.route("/", methods = ['GET', 'POST'])
def index():

    form = UserForm()

    if form.validate_on_submit():
        allEmotionDicts[str(UserForm.url)] = emotionDict
        graphing()
        reset()
        pass
        
    
    return render_template("test.html", form = form)

def graphing():

    counter = 0
    for key, value in allEmotionDicts.items():
        #creates a new figure
        figure = mpl.figure()
        figure.suptitle("Emotions for " + str(key))

        figure, axes = mpl.subplots(1,1) #makes a 1x1 figure

        #setting axis labels
        axes.set_xlabel('Emotions')
        axes.set_ylabel('Seconds')
        axes.set_ylim(0,100)

        #plotting a point - 'bo' means blue plot
        for key2, value2 in value.items():
            axes.plot(key2, value2, 'bo')


        #CREATES FILE ---> CHECK gradesGraph.png
        figure.savefig("graph" + str(counter) + ".png")
        counter+=1

def reset():
    emotionDict = {"joy": 0, "surprise": 0, "sorrow": 0, "anger": 0}

def gen(camera):
    start = time.time()
    while True:
        delay = 3
        if (time.time() - start) >= delay:

            frame = (camera.change_frame())[0]
            emotion = (camera.change_frame())[1]

            if emotion != "":
                emotionDict[emotion] += 1

            print(emotionDict)
            yield (b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
               

@users.route('/video_feed')
def video_feed():
    return Response(gen(VideoCamera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

flask_user/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
       <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

</head>

<body>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">

            <!-- So this next line basically it gets the messages from flash -->
            
            <!-- And then the other categories is the bootstrap, saying that whatever categories get passed will take effect -->

            {% with messages = get_flashed_messages(with_categories=true) %}
                
                {% if messages %}

                <!-- Basically, if the messages exist, loop over the category and message for each message -->
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                    <!-- The {{category}} refers to the string passed in through the category -->
                    {{ message }}

                    </div>
                {% endfor %}

                {% endif %}

            {% endwith %}

            {% block content %}{% endblock %}
            </div>
            
        </div>
    </main>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


</body>

</html>

flask_user/templates/test.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">

    <!-- Means that it will post action to same route as it currently is -->
    <form method="POST" action="">

        <!-- Adds csrs token, this is where the hidden key helps with it -->
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Mindful Me</legend>

            <div class = "form-group">
                <h1>Realtime Emotion</h1>
                <img id="bg" src="{{ url_for('users.video_feed') }}">
            </div>
        
            <div class="form-group">


                <!-- Adding in some bootstrap to the form, label(adds in the css class) -->

                {{ form.url.label(class="form-control-label") }}

                {% if form.url.errors %}

                {{ form.url(class="form-control form-control-lg is-invalid") }}

                    <div class="invalid-feedback">

                        {% for error in form.url.errors %}

                        <span>{{ error }}</span>

                        {% endfor %}

                    </div>

                {% else %}
                {{ form.url(class="form-control formcontrol-lg") }}
                {% endif %}

            </div>

        </fieldset>


        <div class="form-group">
            {{ form.csrf_token }} 
            {{ form.submit(class="btn btn-outline-info") }}

        </div>

        <div class = "form-group">
            <h1>Analysis</h1>
            <img id="bg" src="{{ graph }}">
        </div>

    </form>

</div>

{% endblock content %}